### ISSUE TITLE
Server crash on shortcut

### ISSUE THREAD

**Issue by Kollode** [brainpower-org/cubicle#2]
Server crashes for shortcut CTRL+Shift+C 

```
events.js:183
exercism_1  |       throw er; // Unhandled 'error' event
exercism_1  |       ^
exercism_1  | 
exercism_1  | Error: spawn xterm ENOENT
exercism_1  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
exercism_1  |     at onErrorNT (internal/child_process.js:362:16)
exercism_1  |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
exercism_1  |     at process._tickCallback (internal/process/next_tick.js:181:9)

```

**Comment by marionebl** [comment]
Solved via https://github.com/brainpower-org/cubicle/commit/31ee4770f3b5a57430a706dab53dffe04c534cd6
